### ISSUE TITLE
Create the upload HTML page

### ISSUE THREAD

**Issue by rciampa** [CSUMB-SP17-CST499/VTRMD#23]
Create an html page that includes a `<form>` element to allow uses to upload a CSV file and have it processed and its containing data added to the MySQL database. Users should be able to upload a file by dragging and dropping a CSV (and only a CSV file type) file to a target area of the upload page. 

This page only allows the upload via HTTP/1.1 POST method. The file named  processCvs.inc.php should be posted to from this page to allow the processing and database insertion to happen.

**Where:**
The html file should be saved with a file extension of `.html` and saved in the root `/` directory of the project.

**Comment by brandoncsumb** [comment]
Testing

**Comment by brandoncsumb** [comment]
Drag and drop issue fixed on the upload page. Will push to my fork soon. The upload page is working live at http://hosting.otterlabs.org/salettabrandonl/public_html/VTRMD/upload.html. Processing 
page still needs updating.

**Comment by brandoncsumb** [comment]
Pending review
