### ISSUE TITLE
CSS Selectors

### ISSUE THREAD

**Issue by rciampa** [CSUMB-SP17-CST499/VTRMD#24]
The CSS selector syntax I believe is incorrect in the following sample:

`p[target='Sprint']{
 background-color: yellow;
    border-radius: 25px 25px 25px 25px;
    width: 50px;
    height: 50px;
    text-align: center;
    float: left;
}`

Only `<a>` tags have have a target attribute, there are only a few well defined options for it, utilizing the `target` attribute on other elements will most likely cause validation warnings and scripting errors.

Check [W3Schools  ](https://www.w3schools.com/cssref/css_selectors.asp) or [Mozilla Dev Network](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Selectors)

As I mentioned this afternoon in the lab, almost every element supports the `name` attribute if you would like to try this type of selector, although I prefer other types of selectors for CSS.

**Comment by rjisom** [comment]
[target] is just a selector tag, I found it's easier to read json strings into the document but I can see it being an issue but we can replace it with anything, ex.. [name="T-Mobile"], [selector="Verizon"], [isp="AT&T Services"] .

**Comment by rciampa** [comment]
The brackets `[ ]` are the selector themselves. How they work are `[key=value]`, where a key is a valid attribute for an HTML element and value is a valid entry for that attribute.

Since only a small subset of HTML elements use the `target` attribute it can't be used across all elements as a key attribute.
