### ISSUE TITLE
CVS Processing and SQL repository

### ISSUE THREAD

**Issue by rciampa** [CSUMB-SP17-CST499/VTRMD#5]
We will all need to work against a single db instance that I will host. However, I have provided the SQL files in a zip folder for your own development environments.

[cal_speed_vtrmd_sql.zip](https://github.com/CSUMB-SP17-CST499/VTRMD/files/908489/cal_speed_vtrmd_sql.zip)

Please close this issue once everyone has downloaded the files. Leave a comment as notification of download pls.

**Comment by brandoncsumb** [comment]
How can we connect your database

**Comment by brandoncsumb** [comment]
Downloaded

**Comment by rciampa** [comment]
@brandoncsumb Sample CSV file:

[Sample_Monterey_traceroute_data.zip](https://github.com/CSUMB-SP17-CST499/VTRMD/files/912191/Sample_Monterey_traceroute_data.zip)

**Comment by brandoncsumb** [comment]
Thanks
